version: '3'

services:
  noip:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - TZ=America/Argentina/Buenos aires
      - SUBDOMAINS=tusubdominio
      - TOKEN=11111111111111111
    restart: always


  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  www:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - directorio donde esta el index:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=tuhost.duckdns.org
      - LETSENCRYPT_HOST=tuhost.duckdns.org
      - LETSENCRYPT_EMAIL=tumail@prueba.com
volumes: 
  certs:
  html:
  vhostd:
